- Reshapeing - reshapes an input tensor to a defined shape.
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
- Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
- Squeeze - Remove all 1 dimensions from a tensor.
- Unsqueeze - Add a 1 dimension to a target tensor.
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [1]:
import torch

In [3]:
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [18]:
# Add an extra dimension
x_reshaped = x.reshape(1, -1)   # -1 will automatcally settle
print(x_reshaped)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [19]:
x_reshaped = x.reshape(1, 9)
print(x_reshaped)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [20]:
x_reshaped = x.reshape(9, 1)
print(x_reshaped)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [21]:
x_reshaped = x.reshape(9, -1)
print(x_reshaped)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [24]:
x = torch.arange(1, 13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [25]:
x.reshape(3, 4)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [26]:
x.reshape(4, 3)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [28]:
x.reshape(3, -1) #-1 because here we were not sure what exact dim it will fit all elements.

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Lets say we want to reshape that tensor in such a way that it will have 2 rows.
So we dont know how many column dimension we need to give to exactly reshape.
So we give -1 at last and it will automatically settle for us.

In [30]:
x.reshape(2, -1)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Below we want 1 column but not sure how many row dim it needs to reshape in that way.
So we gave -1.
This shape of data is required in almost every ML project 

In [36]:
x.reshape(-1, 1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])

## View
Return a view of an input tensor of certain shape but keep the same memory as the original tensor.

In [37]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
z = x.view(1, 12)

In [42]:
z

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Now if you change something in z, x will also gets changed as it shares same memory

In [43]:
z[0] = 5

In [44]:
z

tensor([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [45]:
x

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

This is the core difference between reshape and view

# Stack

In [47]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
torch.stack([x, x, x, x, x])

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
torch.stack([x, x, x, x, x], dim = 0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [65]:
torch.stack([x, x, x, x, x], dim = 1)

tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

In [72]:
torch.vstack([x, x, x, x, x])

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [73]:
torch.hstack([x, x, x, x, x])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6,
        7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Squeeze and Unsqueeze

In [76]:
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [79]:
x_reshaped.squeeze()  # Removes a single dimension

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [105]:
x_reshaped.unsqueeze(2)   # Add an extra dimension with unsqueeze

tensor([[[1]],

        [[2]],

        [[3]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]])

## Permute

torch.permute - rearranges the dimensions of a target tensor in a specified order

In [119]:
x_original = torch.rand(size = (224, 224, 3))   # (height, width, color_channels) 
x_original.shape

torch.Size([224, 224, 3])

Permute the original tensor to rearrange the axis (or dim) order

In [120]:
x_permuted = x_original.permute(2, 0, 1)  # 2, 0, 1 is index of original_x size
x_permuted.shape

torch.Size([3, 224, 224])