## Indexing with Pytorch is similar to indexing with Numpy

In [1]:
import torch

In [3]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x = x.reshape(1, 3, 3)  # under tensor/array, it contains 1 3x3 matrix
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [17]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
x[0][0]

tensor([1, 2, 3])

In [22]:
x[0][1]

tensor([4, 5, 6])

In [23]:
x[0][1][1]

tensor(5)

In [26]:
x[0][2][-1]

tensor(9)

In [39]:
x[:, 1]

tensor([[4, 5, 6]])

In [40]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [57]:
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [61]:
x[0][0][:], x[0, 0, :]

(tensor([1, 2, 3]), tensor([1, 2, 3]))